### ISSUE TITLE
Potential logical error

### ISSUE THREAD

**Issue by ZirongCai** [open-component-model/delivery-service#283]
**What happened**:
the delivery-service shows such error

```
2024-12-09 09:51:39,710 [WARNING] k8s.util: no bdba-cfg found for internal
2024-12-09 09:51:39,723 [ERROR] middleware.errors: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/middleware/errors.py", line 20, in middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/middleware/auth.py", line 588, in middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/middleware/db_session.py", line 32, in middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/middleware/route_feature_check.py", line 49, in middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 975, in _iter
    ret = await method()
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/service_extensions.py", line 197, in get
    data=k8s.util.iter_scan_configurations(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/k8s/util.py", line 260, in iter_scan_configurations
    if bdba_cfg:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'bdba_cfg' where it is not associated with a value
```
[original code](https://github.com/open-component-model/delivery-service/blob/b364e690803281aa12da4fc1a46044e147c3756b/k8s/util.py#L254-L261) first tries to get `bdba_cfg` in a try-except logic, but the `bdba_cfg` is anyway accessed later in the if statement which in this case results the error shown above.

Besides that:

my cfg_factory looks like following:
```
{
  "bdba": {
    "internal": {
      "api_url": "https://bdba.tools.sap/",
      "credentials": {
        "auth_scheme": "bearer_token",
        "password": "noop",
        "token": "*",
        "username": "bot_abapcp@protecode-sc.local"
      },
      "group_ids": [
        2758
      ],
      "tls_verify": true
    }
  },
```
so i do not understand why **no bdba-cfg found for internal** error pops up
**What you expected to happen**:

`bdba_cfg` should only be used when try block succeeded.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by 8R0WNI3** [comment]
The affected code path was removed as part of a recent refactoring ([ref](https://github.com/open-component-model/delivery-service/commit/bcb6e11d18d6cbb8fcc1c41e2544665ab12849f7)), hence closing this issue.
